### ISSUE TITLE
Can we have in-line comments?

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/lightspeed-build-website#1]
It would be nice to employ an in-line commenting JS feature so that users to give us an artificial number of snippets, instead of a fixed set.

https://github.com/fedora-copr/lightspeed-build-website/blob/dfd9549b8f8423fb4347d87e576ae1f35e2aa8aa/example2.html#L119

**Comment by FrostyX** [comment]
I just pushed implementation with a dynamic number of snippets.
