### ISSUE TITLE
log analysis - fetch spec files

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/lightspeed-build-website#17]
Implement logic that fetches spec file content from copr, koji, packit, url

**Comment by FrostyX** [comment]
Is this a release blocker?

**Comment by nikromen** [comment]
yep, without it the stored data are incomplete according to our research

**Comment by nikromen** [comment]
in progress - currently I don't have implementation of fetching packit build spec and URL spec

**Comment by praiskup** [comment]
Working now! Koji (srpm, and spec extraction), Copr (direct download), Packit ...
