### ISSUE TITLE
Packit job IDs pointing to Koji builds are not recognized

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/lightspeed-build-website#3]
It's because Packit API provides Koji Task ID and we would ideally need Koji Build ID.
There may not be any blocker but it wasn't straightforward, so I didn't implement it yet.

**Comment by nikromen** [comment]
resolved with https://github.com/fedora-copr/lightspeed-build-website/commit/ea00c27ccc15aefb914e037f57a54d976d06d944

however fetching from koji is currently too slow - #20
